CREATE TABLE [dbo].[Card]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[StartDate] DATETIME NOT NULL,
	[EndDate] DATETIME NOT NULL,
	[CardInfoId] INT NOT NULL,
	CONSTRAINT [FK_Card_CardInfo] FOREIGN KEY ([CardInfoId]) REFERENCES [CardInfo]([Id])
)
